os:
  - linux

sudo: required
language: php

matrix:
  include:
    - php: 7.3
    - php: 7.4
    - php: 8.0

install:
  - composer install

before_script: echo 'phar.readonly = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - composer compile
  - composer test
  - find . -type f ! -path "./.git/*" ! -path "./bin/workspace" ! -path "./bin/build" ! -path "./vendor/*" ! -path "./vendor-bin/*" ! -name "*.phar" ! -name "*.php" -and \( -name "*.sh" -or -perm -0111 \) -exec shellcheck --exclude=SC1008,SC1091 {} +
