os:
  - linux

sudo: required
language: php

php:
  - 7.2

before_install:
  # Manually compile the libsodium library
  - git clone -b stable https://github.com/jedisct1/libsodium.git
  - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..

install:
  # Manually install libsodium, because the TravicCi image doesn't provide PHP7.2 with libsodium
  - pecl install libsodium
  - echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # Add box to allow the my127ws phar to be built
  - wget https://github.com/humbug/box/releases/download/3.0.0-beta.4/box.phar && chmod +x box.phar && sudo mv box.phar /usr/local/bin/box
  - composer install

script: composer test
