
command('global service <name> <action>', 'global service'): |
  #!bash|=
  ws.service ={input.argument('name')} ={input.argument('action')}

command('global config get <key>'): |
  #!bash|=
  echo "={@(input.argument('key'))}"

command('poweroff', 'poweroff'): |
  #!bash(cwd:/)
  ws.poweroff

command('self-update', 'self-update'): |
  #!php
  require_once  'phar://ws.phar/home/bin/ws.update.php';
