
command('global service <name> <action>', 'global service'): |
  #!bash|=
  ws.service ={input.argument('name')} ={input.argument('action')}

command('global list-services'): |
  #!bash
  ws.service.list

command('global config get <key>'): |
  #!bash|=
  echo "={@(input.argument('key'))}"

command('poweroff', 'poweroff'): |
  #!bash(cwd:/)
  ws.poweroff
