
harness.repository('~'):

  magento2:
    latest:
      url: https://github.com/my127/workspace-docker-magento2/tarball/master
      type: tar.gz

  drupal8:
    latest:
      url: https://github.com/my127/workspace-docker-drupal8/tarball/master
      type: tar.gz
